sudo: false

language: go
go_import_path: github.com/hashicorp/vault-ssh-helper

go:
  - 1.11

matrix:
  allow_failures:
    - go:tip

# whitelist master branch
branches:
  only:
    - master

script:
  - make
  - make test
